### ISSUE TITLE
nfs-ganesha-ceph is missing in 3.3-ubuntu1~bionic3

### ISSUE THREAD

**Issue by sparktown** [nfs-ganesha/nfs-ganesha-debian#36]
as said in the title release 3.3-ubuntu1~bionic3 does not include the nfs-ganesha-ceph package which is required to export folders from the ceph file system. The package is present in all the other releases (xenial, eoan, etc.)

**Comment by sparktown** [comment]
Do you need more information from me or did i raise the issue on the wrong project?

I am using the http://ppa.launchpad.net/nfs-ganesha repository

**Comment by kalebskeithley** [comment]
it's not "missing" if Ubuntu doesn't have the correct version of ceph available at the time the ganesha packages are built. ;-)

Apparently Ubuntu has updated ceph since then? I can't/don't monitor Ubuntu or Launchpad to know when they update packages.

This is the right project, but I don't consider "missing packages" to be a genuine issue with these packaging bits. This is for things like files not installed in the right place, missing files in the packages, or non-public executables in /usr/libexec vs /usr/lib/*-linux-gnu, and that sort of thing.

IMO you'd be better served to simply ask in IRC (#ganesha @freenode) or by sending an email to support@lists.nfs-ganesha.org. (You'll robably get a quicker reply anyway.)

Apart from all that, I've respun the packages with FSAL_CEPH enabled, as now it does build. The packages are built and waiting to be published. They may be published by the time you see this.
